### ISSUE TITLE
プロフカードのモデル設計

### ISSUE THREAD

**Issue by SakitaDaiki0623** [SakitaDaiki0623/prof-chan#41]
PF制作で**プロフブロック**というブロックを作成し、それをプロフィール帳に貼り付けるという機能を作成したいと思っています。

【イメージ図】

**プロフィール詳細画面**

![https://i.gyazo.com/cfdd6b273bc16073147d30f12b60a2fb.png](https://i.gyazo.com/cfdd6b273bc16073147d30f12b60a2fb.png)

【詳細】

プロフブロックの項目(items)を入力し、それをプロフィールの上に貼り付ける仕様にしたいです。

プロフブロックを貼り付ける流れとしては、登録されたフォーマット(Qustion, Ranking)を選択し、そのフォーマットの中で登録されているものをタイトル(IF...など)から選択します。そして、自分の回答を記入しプロフィールに登録して表示します。

こちらのプロフブロックはユーザーが自分で好きなコブロックを作成できるようにしたいと考えています。

【可能であれば実装したい機能】

- プロフブロックは配置場所の入れ替えが可能(こちらの方が実装したい)

上記のプロフブロック機能を作成するためのDBを設計したですが、複雑な構造になったため、DB設計についてアドバイスをいただきたくPRした次第です。

## 作成したDB設計

下記のリンクに作成したDB設計を反映しております。

[https://drive.google.com/file/d/1KOV9rxuvCUenZRAJKHCQqWX77uQjO_N7/view?usp=sharing](https://drive.google.com/file/d/1KOV9rxuvCUenZRAJKHCQqWX77uQjO_N7/view?usp=sharing)

【スクショ】

![https://i.gyazo.com/00c06e451e9b5b348ec10bc1037135c8.png](https://i.gyazo.com/00c06e451e9b5b348ec10bc1037135c8.png)

## 各テーブルについて必要だと判断した理由

プロフブロック機能のためのテーブルとそれをDBに反映した理由を記載します。

- usersテーブル

    こちらに関しては、プロフブロックをユーザーが自由に作成できない場合は不要になります。作成者が誰であるかを明示したいため作成しております。

- profile_blocksテーブル

    プロフィールから見てブロックは多数持つことになると思います。ブロックに関しても作成されたフォーマットのブロックは複数のプロフィールで使われるため、プロフィールを多数持つことになると思います。多 : 多の関係になるため中間テーブルを設けました。各フォーマットごとに中間テーブルを作るのではなく(profile_text_blocks)、中間テーブルに関しては1つにまとめるています。

    ![https://i.gyazo.com/f0e1597987ce818b2b754049a2cf7f70.png](https://i.gyazo.com/f0e1597987ce818b2b754049a2cf7f70.png)

フォーマットごとのテーブルの詳細を説明します。

- qustion_blocks, question_itemsテーブル

qustion_blockに対して質問内容と回答のカラムを持つquestion_itemsをhas_manyの関係でアソシエーション

![https://i.gyazo.com/d1e31e56854da1bf16d05a6dbce94a1d.png](https://i.gyazo.com/d1e31e56854da1bf16d05a6dbce94a1d.png)

contentカラム = 「芸能人になれるとしたら何になりたい?」

answerカラム = 長い下線のところにユーザーが回答する

[Questionフォーマット]

![https://i.gyazo.com/bd51cc2ae5f6a325fd3b4dc16b08b3d5.png](https://i.gyazo.com/bd51cc2ae5f6a325fd3b4dc16b08b3d5.png)

- yes_or_no_blocks, yes_or_no_itemsテーブル

アソシエーションの理由は上記のQuestionのプロフブロックと同じです。

Yes or Noですので回答のカラムは`boolean`型にしています。

![https://i.gyazo.com/a43580e629beb6d3fef367a59d4a752e.png](https://i.gyazo.com/a43580e629beb6d3fef367a59d4a752e.png)

[Yes or Noフォーマット]

![https://i.gyazo.com/658cc632a8f791ba65bab7bc7598dce5.png](https://i.gyazo.com/658cc632a8f791ba65bab7bc7598dce5.png)

- ranking_blocks, ranking_itemsテーブル

こちらもアソシエーションの理由は上記のQuestionのプロフブロック等と同じです。

![https://i.gyazo.com/8f2031bbd1c1a40ecfc6296fdf180616.png](https://i.gyazo.com/8f2031bbd1c1a40ecfc6296fdf180616.png)

[Rankingフォーマット]

![https://i.gyazo.com/065c7588a63bb5324ab1c4b8ac268e90.png](https://i.gyazo.com/065c7588a63bb5324ab1c4b8ac268e90.png)

- text_blocksテーブル
    - 自己紹介などの長い文章を一つ書くためのフォーマットのテーブル
    - 項目はテキスト1つのため外部テーブルを使用せずテーブルのカラムに保存

![https://i.gyazo.com/f9ff9433c3217eae835383af1fc865c0.png](https://i.gyazo.com/f9ff9433c3217eae835383af1fc865c0.png)

[Textフォーマット]

![https://i.gyazo.com/e1a224114b6b9ece300a36a155fda0d4.png](https://i.gyazo.com/e1a224114b6b9ece300a36a155fda0d4.png)

## コメント
長くなりましたが、相談したいこととしては以下の点です。
- 機能を実現するためのDB設計として問題なさそうか
- DB設計をより簡略化できないか

何かご不明点な点がありましたらお教えください。

**Comment by SakitaDaiki0623** [comment]
## DB設計の変更

申し訳ございません。

上記のDB設計を変更しましたので上述したものではなく最新のDB設計を参照いただきますでしょうか。

https://drive.google.com/file/d/1KOV9rxuvCUenZRAJKHCQqWX77uQjO_N7/view?usp=sharing


[最新のDB]

![https://i.gyazo.com/7e1c21cc4a5f586bdb933bdb47f88b8e.png](https://i.gyazo.com/7e1c21cc4a5f586bdb933bdb47f88b8e.png)

## 変更理由

変更理由としてはプロフブロックの仕様を下記の通り変更したためです。

---

**[変更前] ユーザー間で作ったプロフブロックを他のユーザーが使えるようにシェアできる**

⇒ 多 : 多の関係

![https://i.gyazo.com/f0e1597987ce818b2b754049a2cf7f70.png](https://i.gyazo.com/f0e1597987ce818b2b754049a2cf7f70.png)

↓

**[変更後] ユーザーがプロフブロックをシェアせず、個人だけのプロフカードを作成する**

⇒ 1 : 多の関係

![https://i.gyazo.com/3afac3b6f2d779e97bc53948ed3c4740.png](https://i.gyazo.com/3afac3b6f2d779e97bc53948ed3c4740.png)

---

そのため、プロフブロックからのアソシエーションがbelongs_toに変わるため、下記のような多 : 多の関係がなくなりました。

新しいアソシエーションとして以下の関係にしました。

- `user has_one profile_blocks`
- `profile_block has_many hoge_blocks`

これは`user has_many  hoge_blocks`とすることでユーザーのモデルで多くの`has_many`に関する記述を避けるために、その代わりとなる`profile_blocks`を作りました。

最初の質問時にお送りした多 : 多の関係はすこし実装が難しそうでしたので、プロフブロックをシェアせず自分だけが使うこちらの仕様にきりかえました。

2度コメントしたため少しややこしく申し訳ございませえんが、何か実装に関してアドバイスがありましたら、ご教示いただきたいです。

**Comment by DaichiSaito** [comment]
めっちゃ複雑ですね！！！これはむずい！！

> 登録されたフォーマット(Qustion, Ranking)を選択し、そのフォーマットの中で登録されているものをタイトル(IF...など)から選択します。

これは運営側が事前に作っておくイメージですか？
また、「芸能人になれるなら誰になりたい？」や「人見知り？」などの選択肢はユーザーが自由に登録できるイメージですか？それともそれも運営側が事前に作っておくイメージ？

@SakitaDaiki0623

**Comment by SakitaDaiki0623** [comment]
@DaichiSaito 
> 「芸能人になれるなら誰になりたい？」や「人見知り？」などの選択肢はユーザーが自由に登録できるイメージ
今のところはユーザー側が選択肢を登録できるイメージで合っています！運営側が用意する方が楽だとは思うんですけど、、

その登録された選択肢はそのユーザーだけで使える使用です。他のユーザーが使えない方がユーザー : ブロックの関係が`1 : 多`になると思いまして、そちらの方がシンプルになるのかなと思いました。

**Comment by DaichiSaito** [comment]
すんません、わかりづらい質問だったかも！
> その登録された選択肢は

これが誰が入力するのかが知りたかったです！運営が事前に決め打ちしておくのか、ユーザーに自由に作ってもらうのか。

Aさんは「芸能人になれるなら誰になりたい？」と「誰とでも一度デートできるなら誰とする？」という選択肢を用意。
Bさんは「宝くじで1億円当たったら何する？」と「無人島に持ってとしたら何持ってく？」という選択肢を用意。

という認識で良いのかな？
@SakitaDaiki0623

**Comment by SakitaDaiki0623** [comment]
申し訳ございません💦

ユーザーが自由に選択肢を作れる仕様の認識でお間違い無いです！
@DaichiSaito

**Comment by DaichiSaito** [comment]
今の設計って
「芸能人になれるならだれになりたい？」と「誰とでも一度デートできるなら誰とする？」の二つの選択肢を作る場合は`profile_block`に一つ、`question_block`に二つレコードがインサートされるイメージですか？

また、`question_item`や`ranking_item`の`answer`ってなんでしたっけ？`content`との棲み分けを教えてください！

@SakitaDaiki0623

**Comment by SakitaDaiki0623** [comment]
>「芸能人になれるならだれになりたい？」と「誰とでも一度デートできるなら誰とする？」の二つの選択肢を作る場合はprofile_blockに一つ、question_blockに二つレコードがインサートされるイメージですか？

二つの選択肢を作る場合、`question_block`に一つ、`question_items`に二つのレコードが挿入されるですかね。

テーブルの役割としては下記のような想定です。
* `profile_block`
ユーザーのプロフブロックをまとめるための役割
(ユーザーが`has_many question_blocks`, `has_many ranking_blocks`とすることも可能ですが、ユーザーから伸びるアソシエーションが多くなってしまうため、`profile_block`というレコードを`user has_one profile_block`という関係で`profile_block`を用意しています。)

* `question_blocks`, `ranking_blocks`, etc...
ブロック本体
回答と選択肢をセットで含んだ`hoge_items`を持つ(最大3つまで`hoge_items`を持てるように制御)

[question_block]
[![Image from Gyazo](https://i.gyazo.com/15a1e403896868068e8ddef95c37168b.png)](https://gyazo.com/15a1e403896868068e8ddef95c37168b)


* `question_items`, `ranking_items`, etc...
選択肢(`content`)とそれに対する回答(`answer`)をセットで含んだもの

`question_items`
[![Image from Gyazo](https://i.gyazo.com/17ce748e1203e8e3acecff0d35a68540.png)](https://gyazo.com/17ce748e1203e8e3acecff0d35a68540)

それぞれの関係を表すと下記画像のようなイメージです！

[![Image from Gyazo](https://i.gyazo.com/53b31741d807efa949a522df3cbe812c.png)](https://gyazo.com/53b31741d807efa949a522df3cbe812c)

---

> また、question_itemやranking_itemのanswerってなんでしたっけ？contentとの棲み分けを教えてください！

こちらに関しては上記で説明した通りです。
`question_item`の`answer`は回答で、`content`は選択肢です！
contentの命名が相応しくなく、わかりづらかったかもしれません、、💦

**Comment by DaichiSaito** [comment]
なるほど！理解しました！
めちゃわかりやすい図の共有ありがとうございました！

> 機能を実現するためのDB設計として問題なさそうか

→ 問題ないと思いますね！めちゃ複雑な設計だけどよく作りましたね！

> DB設計をより簡略化できないか

→ 自分も実務で使ったことはないんですが、JSON型を使うと簡略化できるとは思いますよ。ただ正規化を崩すことになったりその他諸々デメリットもあるので一概にはおすすめできないです！

もしJSON型を使うのであれば
- question_blocks
  - title:string
  - question_items:json

というスキーマになるかなー。
データ構造はこんなイメージ↓

```
{
  id: 1,
  title: "IF..."
  question_items: [
    { content: "芸能人になれるなら？", answer: "氷室京介" },
    { content: "誰とでも一度デートできるなら誰とする？", answer: "布袋寅泰" },
    { content: "天国にもってくとしたら？", answer: "現場Rails" },
  ]
}
```

みたいな感じ。

正直なことを言うと検索とか集計をするわけでもないと思うのでJSON型でも良いとは思います笑
が、先田さんの設計みたいにちゃんと正規化した場合はjoinとかいろいろ学べるのでより勉強にはなると思います！どうするかは先田さん次第笑
個人的にはJSON型に逃げるのではなく正規化パターンでチャレンジしてもらいたい笑

**Comment by SakitaDaiki0623** [comment]
確認いただきありがとうございます！

> → 問題ないと思いますね！めちゃ複雑な設計だけどよく作りましたね！

よかったです！このまま進めてみます！

> 先田さんの設計みたいにちゃんと正規化した場合はjoinとかいろいろ学べるのでより勉強にはなると思います！どうするかは先田さん次第笑
個人的にはJSON型に逃げるのではなく正規化パターンでチャレンジしてもらいたい笑

これは、、、圧を感じますねww
JSON型については一旦心に留めておいて正規化でチャレンジしてみます！笑

一旦DB設計の相談についてはクローズでお願いします！！

issueについてはopenのままにしておきます。
また詰まったらこちらで相談します！

ps 天国に持っていくとしたら現場Railsはめちゃ笑いましたww

@DaichiSaito
